---
- name: check every 60 seconds for 10 attempts if openvidu is up and ready
  uri:
    url: 'https://localhost/inspector/'
    validate_certs: false
    return_content: yes
    timeout: 2
  register: openvidu_result
  until: openvidu_result['status']|default(0) == 200
  retries: 10
  delay: 60
