---
- name: stop supervisor
  systemd: 
    name: supervisor 
    state: stopped

- name: start supervisor
  systemd: 
    name: supervisor 
    state: started

- name: restart supervisor
  systemd: 
    name: supervisor 
    state: restarted

