---
- name: start nginx
  systemd: 
    name: nginx
    state: started

- name: stop nginx
  systemd: 
    name: nginx
    state: stopped

- name: restart nginx
  systemd: 
    name: nginx 
    state: restarted

