---
- name: copying script for health check
  copy:
    src: "openvidu_healthcheck.sh"
    dest: "/usr/local/bin"
    mode: "0755"

- name: execute health check
  shell: /usr/local/bin/openvidu_healthcheck.sh
  register: healthcheck

- debug: var=healthcheck.stdout_lines
