---
- name: creating working dir
  file:
    path: "/opt/openvidu"
    state: "directory"
    mode: 0755

- name: registering openvidu systemd service
  copy:
    src: "openvidu.service"
    dest: "/etc/systemd/system/openvidu.service"

- name: installing Java 8
  apt:
    name: openjdk-8-jdk
    update_cache: yes
  when: install_software|bool

- name: installing Redis
  apt:
    name: redis-server
  notify: restart redis
  when: install_software|bool

- name: download OpenVidu JAR file
  get_url:
    url: https://pro.openvidu.io/openvidu-server-pro-{{ openvidu_version }}.jar
    dest: /opt/openvidu/openvidu-server.jar
    mode: u+rwx
    owner: "{{ openvidu_user }}"
    group: "{{ openvidu_group }}"
    username: "{{ openvidu_pro_username }}"
    password: "{{ openvidu_pro_password }}"
  when: install_software|bool

- name: copying openvidu launch script
  template:
    src: "openvidu-server.sh"
    dest: "/usr/local/bin"
    mode: "u+rwx"

- name: copying launch media server script
  template:
    src: "launch_kms.sh.j2"
    dest: "/usr/local/bin/launch_kms.sh"
    mode: "0755"

- name: copying remove media server script
  template:
    src: "remove_kms.sh.j2"
    dest: "/usr/local/bin/remove_kms.sh"
    mode: "0755"

- name: copying openvidu application.properties
  template:
    src: "application.properties.j2"
    dest: "/opt/openvidu/application.properties"
    mode: "u+rwx"
  notify: restart openvidu

- name: copying script for aws signal
  copy:
    src: "check_app_ready.sh"
    dest: "/usr/local/bin"
    mode: "0755"
  when: run_ec2|bool

- name: creating recording directory
  file:
    path: "/opt/openvidu/recordings"
    state: "directory"
    mode: "0777"

- name: registering who i am
  copy:
    src: "openvidu-cluster-member"
    dest: "/opt/openvidu"
