---
- name: creating working dir
  file:
    path: "/opt/openvidu"
    state: "directory"
    mode: 0755

- name: registering openvidu systemd service
  copy:
    src: "openvidu.service"
    dest: "/etc/systemd/system/openvidu.service"

- name: installing Java 8
  apt:
    name: openjdk-8-jdk
    update_cache: yes
  when: install_software|bool

- name: installing Redis
  apt:
    name: redis-server
  notify: restart redis
  when: install_software|bool

- name: copying script to auto register DNS name
  template:
    src: "openvidu_route53_manager.sh.j2"
    dest: "/usr/local/bin/openvidu_route53_manager.sh"
    mode: "755"
  when: whichcert == "customcert"

- name: auto registering DNS name
  shell: /usr/local/bin/openvidu_route53_manager.sh
  
- name: download OpenVidu JAR file
  get_url:
    url: https://pro.openvidu.io/openvidu-server-pro-{{ openvidu_version }}.jar
    dest: /opt/openvidu/openvidu-server.jar
    mode: u+rwx
    owner: "{{ openvidu_user }}"
    group: "{{ openvidu_group }}"
    username: "{{ openvidu_pro_username }}"
    password: "{{ openvidu_pro_password }}"
  when: install_software|bool

- name: copying openvidu launch script
  template:
    src: "openvidu-server.sh"
    dest: "/usr/local/bin"
    mode: "u+rwx"

- name: creating cluster directory
  file:
    path: "/opt/openvidu/cluster/{{ openvidu_pro_cluster_environment }}"
    state: "directory"
    mode: "0777"
  when: openvidu_pro_cluster_environment != "on_premises"

- name: creating cluster output directory
  file:
    path: "/opt/openvidu/cluster/output"
    state: "directory"
    mode: "0777"

- name: copying launch media server script
  template:
    src: "openvidu_launch_kms.sh.j2"
    dest: "/opt/openvidu/cluster/{{ openvidu_pro_cluster_environment }}/openvidu_launch_kms.sh"
    mode: "0755"
  when: openvidu_pro_cluster_environment != "on_premises"

- name: copying remove media server script
  template:
    src: "openvidu_drop.sh.j2"
    dest: "/opt/openvidu/cluster/{{ openvidu_pro_cluster_environment }}/openvidu_drop.sh"
    mode: "0755"
  when: openvidu_pro_cluster_environment != "on_premises"

- name: copying get security group for media server script
  template:
    src: "openvidu_get_security_group_id.sh.j2"
    dest: "/opt/openvidu/cluster/{{ openvidu_pro_cluster_environment }}/openvidu_get_security_group_id.sh"
    mode: "0755"
  when: openvidu_pro_cluster_environment != "on_premises"

- name: copying auto discover media servers script
  template:
    src: "openvidu_autodiscover.sh.j2"
    dest: "/opt/openvidu/cluster/{{ openvidu_pro_cluster_environment }}/openvidu_autodiscover.sh"
    mode: "0755"
  when: openvidu_pro_cluster_environment != "on_premises"

- name: copying configuration file
  template:
    src: "openvidu.rc.j2"
    dest: "/opt/openvidu/cluster/openvidu.rc"
    mode: "0644"
  when: openvidu_pro_cluster_environment != "on_premises"

- name: copying openvidu application.properties
  template:
    src: "application.properties.j2"
    dest: "/opt/openvidu/application.properties"
    mode: "u+rwx"
  notify: restart openvidu

- name: copying script for aws signal
  copy:
    src: "check_app_ready.sh"
    dest: "/usr/local/bin"
    mode: "0755"
  when: run_ec2|bool

- name: creating recording directory
  file:
    path: "/opt/openvidu/recordings"
    state: "directory"
    mode: "0777"

- name: registering who i am
  copy:
    src: "openvidu-cluster-member"
    dest: "/opt/openvidu"

- name: creating custom-layout directory
  file:
    path: /opt/openvidu/custom-layout
    state: directory
    mode: 0755