---
- name: start kibana
  systemd: 
    name: kibana
    state: started
    enabled: true

- name: stop kibana
  systemd: 
    name: kibana
    state: stopped

- name: restart kibana
  systemd: 
    name: kibana
    state: restarted
    enabled: true

- name: restart elasticsearch
  systemd: 
    name: elasticsearch
    state: restarted
    enabled: true